import json
from pathlib import Path

notebook = {
    'nbformat': 4,
    'nbformat_minor': 0,
    'metadata': {
        'colab': {
            'name': 'CopyAir - Colab Training & Inference Studio',
            'provenance': [],
            'gpuType': 'T4'
        },
        'kernelspec': {
            'name': 'python3',
            'display_name': 'Python 3'
        },
        'language_info': {
            'name': 'python'
        },
        'accelerator': 'GPU'
    },
    'cells': [
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '# 🎬 CopyAir / NeuralShot - Google Colab Training & Inference Studio\n',
                '\n',
                '[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Serces19/copyair/blob/main/notebooks/copyair_colab_training.ipynb)\n',
                '\n',
                'Bienvenido al entorno de ejecución en la nube para **CopyAir**: el motor SOTA de **Image-to-Image translation** orientado a VFX, Restauración y De-Aging.\n',
                '\n',
                '### 📌 ¿Qué incluye este Notebook?\n',
                '1. **Setup Acelerado por GPU & Sincronización Directa con Google Drive Desktop** (`/content/drive/Othercomputers/My Computer/Tesis/datasets`).\n',
                '2. **Detección Automática de Datasets de Tesis**: `deaging`, `wireremoval`, `car_reflejo`, `reflections`.\n',
                '3. **Catálogo SOTA Oficial**: NAFNet, Restormer (MDTA), ScopeUNet (Lossless PixelUnshuffle + ICNR), ConvNeXt-V2, MambaIR (SS2D), Residual U-Net.\n',
                '4. **Configurador de Hiperparámetros y Pérdidas Híbridas** (LPIPS, Charbonnier, DINO, Laplacian).\n',
                '5. **MLflow Offline/Local** (`sqlite:///mlflow.db`): Registra métricas, parámetros y checkpoints en `mlruns/` sin depender de servidores en vivo.\n',
                '6. **Estudio de Inferencia HD/4K (Tiled)** para procesar imágenes, secuencias y videos completos sin Out-Of-Memory (OOM).'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 1. ⚙️ Hardware Check & Montaje de Google Drive\n',
                '\n',
                'Verificamos la GPU asignada (T4, V100, A100 o L4) y montamos Google Drive. Tus datasets sincronizados desde la PC mediante **Google Drive Desktop** estarán disponibles de inmediato.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# 1. Comprobar GPU\n',
                '!nvidia-smi\n',
                '\n',
                'import torch\n',
                'print(f"\\n🔥 PyTorch Version: {torch.__version__}")\n',
                'print(f"🚀 CUDA Available: {torch.cuda.is_available()}")\n',
                'if torch.cuda.is_available():\n',
                '    print(f"🎮 GPU Name: {torch.cuda.get_device_name(0)}")\n',
                '    vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n',
                '    print(f"💾 VRAM Total: {vram_gb:.2f} GB")\n',
                'else:\n',
                '    print("⚠️ ADVERTENCIA: No se detectó GPU. Ve a Entorno de ejecución -> Cambiar tipo de entorno -> T4 GPU")'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# 2. Montar Google Drive\n',
                'import os\n',
                'from pathlib import Path\n',
                '\n',
                'try:\n',
                '    from google.colab import drive\n',
                '    drive.mount("/content/drive")\n',
                '    print("✓ Google Drive montado exitosamente en /content/drive")\n',
                'except Exception as e:\n',
                '    print(f"Nota: {e}")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 2. 📦 Clonar Repositorio e Instalar Dependencias\n',
                '\n',
                'Usamos `uv` para una instalación ultrarrápida y determinista del código sincronizado de CopyAir y sus dependencias.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import os\n',
                'from pathlib import Path\n',
                '\n',
                '# Clonar el repositorio si no existe en el directorio de trabajo\n',
                'REPO_DIR = Path("/content/copyair")\n',
                'if not REPO_DIR.exists():\n',
                '    !git clone https://github.com/Serces19/copyair.git /content/copyair\n',
                '    %cd /content/copyair\n',
                'else:\n',
                '    %cd /content/copyair\n',
                '    !git pull\n',
                '\n',
                '# Instalar uv y requerimientos\n',
                '!pip install -q uv\n',
                '!uv pip install --system -r requirements.txt\n',
                '\n',
                'print("\\n✓ Entorno y dependencias de CopyAir instaladas exitosamente!")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 3. 📂 Explorador y Detector Automático de Datasets en Google Drive\n',
                '\n',
                'Esta celda escanea automáticamente las rutas de **Google Drive Desktop** para localizar tus datasets (`deaging`, `wireremoval`, `car_reflejo`, `reflections`).'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import glob\n',
                'from pathlib import Path\n',
                '\n',
                '# Rutas candidatas habituales en Google Drive Desktop\n',
                'POSSIBLE_ROOTS = [\n',
                '    Path("/content/drive/Othercomputers/My Computer/Tesis/datasets"),\n',
                '    Path("/content/drive/Othercomputers/Mi PC/Tesis/datasets"),\n',
                '    Path("/content/drive/MyDrive/Tesis/datasets"),\n',
                '    Path("/content/drive/MyDrive/datasets"),\n',
                '    Path("data/01_raw")\n',
                ']\n',
                '\n',
                'DATASET_ROOT_FOUND = None\n',
                'for root in POSSIBLE_ROOTS:\n',
                '    if root.exists():\n',
                '        DATASET_ROOT_FOUND = root\n',
                '        break\n',
                '\n',
                'if DATASET_ROOT_FOUND is None:\n',
                '    # Búsqueda dinámica en Othercomputers\n',
                '    other_comps = list(glob.glob("/content/drive/Othercomputers/*/**/datasets", recursive=True))\n',
                '    if other_comps:\n',
                '        DATASET_ROOT_FOUND = Path(other_comps[0])\n',
                '\n',
                'print(f"📁 Directorio de Datasets detectado: {DATASET_ROOT_FOUND}\\n")\n',
                '\n',
                'if DATASET_ROOT_FOUND and DATASET_ROOT_FOUND.exists():\n',
                '    datasets = [d for d in DATASET_ROOT_FOUND.iterdir() if d.is_dir()]\n',
                '    print("📊 Datasets disponibles:")\n',
                '    for d in datasets:\n',
                '        in_p = d / "input"\n',
                '        gt_p = d / "gt"\n',
                '        ext_p = d / "extracted_frames"\n',
                '        n_in = len(list(in_p.glob("*.png")) + list(in_p.glob("*.jpg"))) if in_p.exists() else 0\n',
                '        n_gt = len(list(gt_p.glob("*.png")) + list(gt_p.glob("*.jpg"))) if gt_p.exists() else 0\n',
                '        n_ext = len(list(ext_p.glob("*.png")) + list(ext_p.glob("*.jpg"))) if ext_p.exists() else 0\n',
                '        print(f"  • [{d.name}]: {n_in} pares de entrenamiento (input/gt) | {n_ext} frames extraídos de video")\n',
                'else:\n',
                '    print("⚠️ No se encontró la carpeta automática. Podrás escribir la ruta manualmente abajo.")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 4. 🧠 Guía de Modelos y Generador Interactivo de Configuración\n',
                '\n',
                'Selecciona la arquitectura y el dataset para generar `configs/params.yaml`:\n',
                '\n',
                '| Modelo | Variante recomendada | Fortalezas principales |\n',
                '|---|---|---|\n',
                '| **`nafnet`** | `base` / `small` | **Recomendado SOTA General**. Sin activaciones complejas (SimpleGate), LayerScale, ultrarrápido y preserva texturas finas. |\n',
                '| **`restormer`** | `small` / `tiny` | **Recomendado SOTA Transformer**. Multi-Dconv Head Transposed Attention (MDTA) con complejidad $O(HW)$ + GDFN. |\n',
                '| **`scope_unet`** | `base` / `small` | **Anti-Checkerboard**. Downsample sin pérdida con `PixelUnshuffle` + Upsample `ICNR PixelShuffle`. |\n',
                '| **`convnext`** | `tiny` / `nano` | Gran campo receptivo (7x7 depthwise), regularización DropPath, decoder con GroupNorm + GRN. |\n',
                '| **`mambair`** | `base` / `tiny` | State-Space Model 2D (SS2D) en 4 direcciones transversales con memoria lineal. |\n',
                '| **`residual_unet`** | `base_channels: 64` | Baseline robusto y rápido con Pre-Act Mish, GroupNorm, Dilated Bottleneck y atajos de identidad puros. |\n',
                '\n',
                '> **Nota sobre MLflow:** La configuración se genera automáticamente con `tracking_uri: "sqlite:///mlflow.db"`, registrando todos los runs en `./mlruns` de forma 100% nativa y sin necesidad de abrir puertos ni servidores.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import yaml\n',
                'from pathlib import Path\n',
                '\n',
                '# =========================================================================\n',
                '# 🎛️ 1. SELECCIÓN DE DATASET (GOOGLE DRIVE DESKTOP O LOCAL)\n',
                '# =========================================================================\n',
                'DATASET_NAME = "deaging"  # @param ["deaging", "wireremoval", "car_reflejo", "reflections", "custom"]\n',
                'CUSTOM_DATASET_ROOT = "/content/drive/Othercomputers/My Computer/Tesis/datasets"  # @param {type:"string"}\n',
                '\n',
                '# Resolver directorios\n',
                'if DATASET_NAME != "custom":\n',
                '    base_p = Path(CUSTOM_DATASET_ROOT) / DATASET_NAME\n',
                '    if not base_p.exists() and DATASET_ROOT_FOUND:\n',
                '        base_p = DATASET_ROOT_FOUND / DATASET_NAME\n',
                '    INPUT_DIR = str(base_p / "input")\n',
                '    GT_DIR = str(base_p / "gt")\n',
                '    FRAMES_DIR = str(base_p / "extracted_frames")\n',
                'else:\n',
                '    INPUT_DIR = f"{CUSTOM_DATASET_ROOT}/input"\n',
                '    GT_DIR = f"{CUSTOM_DATASET_ROOT}/gt"\n',
                '    FRAMES_DIR = f"{CUSTOM_DATASET_ROOT}/extracted_frames"\n',
                '\n',
                'OUTPUT_DIR = f"output_inference/{DATASET_NAME}"\n',
                '\n',
                '# =========================================================================\n',
                '# 🎛️ 2. SELECTOR DE ARQUITECTURA Y PRESETS SOTA\n',
                '# =========================================================================\n',
                '# Opciones de ARCHITECTURE: "nafnet", "restormer", "scope_unet", "convnext", "mambair", "residual_unet", "modern_unet", "smart_unet", "basic_unet"\n',
                'SELECTED_ARCH = "nafnet"  # @param ["nafnet", "restormer", "scope_unet", "convnext", "mambair", "residual_unet", "modern_unet", "smart_unet", "basic_unet"]\n',
                'MODEL_SIZE = "base"       # @param ["nano", "tiny", "small", "base", "large"]\n',
                'EPOCHS = 1000             # @param {type:"integer"}\n',
                'BATCH_SIZE = 4            # @param {type:"integer"}\n',
                'LEARNING_RATE = 0.001     # @param {type:"number"}\n',
                'IMG_SIZE = 512            # @param {type:"integer"}\n',
                '\n',
                '# Construir diccionario de configuración base\n',
                'config = {\n',
                '    "data": {\n',
                '        "input_dir": INPUT_DIR,\n',
                '        "gt_dir": GT_DIR,\n',
                '        "frames_dir": FRAMES_DIR if Path(FRAMES_DIR).exists() else INPUT_DIR,\n',
                '        "output_dir": OUTPUT_DIR,\n',
                '        "models_dir": "models"\n',
                '    },\n',
                '    "model": {\n',
                '        "architecture": SELECTED_ARCH,\n',
                '        "size": MODEL_SIZE,\n',
                '        "in_channels": 3,\n',
                '        "out_channels": 3,\n',
                '        "dropout_p": 0.05\n',
                '    },\n',
                '    "training": {\n',
                '        "epochs": EPOCHS,\n',
                '        "batch_size": BATCH_SIZE,\n',
                '        "learning_rate": LEARNING_RATE,\n',
                '        "weight_decay": 1e-4,\n',
                '        "mixed_precision": True,\n',
                '        "gradient_accumulation_steps": 1,\n',
                '        "clear_cache_every_n_epochs": 10,\n',
                '        "optimizer": {\n',
                '            "type": "adamw",\n',
                '            "beta1": 0.9,\n',
                '            "beta2": 0.999\n',
                '        },\n',
                '        "scheduler": {\n',
                '            "type": "cosine",\n',
                '            "params": {\n',
                '                "T_max": EPOCHS,\n',
                '                "eta_min": 1e-6\n',
                '            }\n',
                '        },\n',
                '        "val_split": 0,\n',
                '        "val_interval": 50,\n',
                '        "val_samples": 4,\n',
                '        "viz_interval": 100,\n',
                '        "save_interval": 250,\n',
                '        "early_stopping_patience": 500\n',
                '    },\n',
                '    "loss": {\n',
                '        "lambda_l1": 0.0,\n',
                '        "lambda_charbonnier": 0.2,\n',
                '        "lambda_perceptual": 0.8,\n',
                '        "lambda_laplacian": 0.1,\n',
                '        "lambda_dino": 0.2,\n',
                '        "lambda_ssim": 0.0,\n',
                '        "lambda_ffl": 0.0,\n',
                '        "lambda_dreamsim": 0.0,\n',
                '        "lambda_sobel": 0.0\n',
                '    },\n',
                '    "gan": {\n',
                '        "enabled": False,\n',
                '        "lambda_gan": 0.01,\n',
                '        "lambda_feature_matching": 10,\n',
                '        "discriminator": {\n',
                '            "lr": 1e-4,\n',
                '            "n_layers": 3\n',
                '        }\n',
                '    },\n',
                '    "augmentation": {\n',
                '        "enabled": True,\n',
                '        "img_size": IMG_SIZE,\n',
                '        "horizontal_flip_p": 0.5,\n',
                '        "vertical_flip_p": 0.0,\n',
                '        "rotation_limit": 10,\n',
                '        "gaussian_noise_p": 0.0,\n',
                '        "gaussian_blur_p": 0.05,\n',
                '        "color_jitter_p": 0.05\n',
                '    },\n',
                '    "device": "cuda",\n',
                '    "num_workers": 2,\n',
                '    "pin_memory": True,\n',
                '    "logging": {\n',
                '        "level": "INFO",\n',
                '        "log_dir": "logs"\n',
                '    },\n',
                '    "mlflow": {\n',
                '        "enabled": True,\n',
                '        "experiment_name": f"copyair_{DATASET_NAME}_{SELECTED_ARCH}_{MODEL_SIZE}",\n',
                '        "tracking_uri": "sqlite:///mlflow.db"\n',
                '    },\n',
                '    "inference": {\n',
                '        "target_fps": 24,\n',
                '        "frame_sample_rate": 1\n',
                '    }\n',
                '}\n',
                '\n',
                '# Ajustes específicos por arquitectura\n',
                'if SELECTED_ARCH == "nafnet":\n',
                '    config["model"]["size"] = MODEL_SIZE if MODEL_SIZE in ["small", "base", "large"] else "base"\n',
                'elif SELECTED_ARCH == "restormer":\n',
                '    config["model"]["size"] = MODEL_SIZE if MODEL_SIZE in ["tiny", "small", "base"] else "small"\n',
                '    config["training"]["learning_rate"] = 3e-4\n',
                'elif SELECTED_ARCH in ["scope_unet", "gated_unet"]:\n',
                '    config["model"]["size"] = MODEL_SIZE if MODEL_SIZE in ["small", "base"] else "base"\n',
                'elif SELECTED_ARCH == "convnext":\n',
                '    config["model"]["size"] = MODEL_SIZE if MODEL_SIZE in ["nano", "tiny", "small", "base"] else "tiny"\n',
                '    config["model"]["drop_path_rate"] = 0.10\n',
                'elif SELECTED_ARCH in ["mambair", "vmamba"]:\n',
                '    config["model"]["size"] = MODEL_SIZE if MODEL_SIZE in ["tiny", "base", "large"] else "base"\n',
                '    config["training"]["learning_rate"] = 5e-4\n',
                'elif SELECTED_ARCH == "residual_unet":\n',
                '    config["model"].update({\n',
                '        "base_channels": 64,\n',
                '        "norm_type": "group",\n',
                '        "activation": "mish",\n',
                '        "groups": 32,\n',
                '        "residual": {"use_dilated_bottleneck": True}\n',
                '    })\n',
                'elif SELECTED_ARCH == "modern_unet":\n',
                '    config["model"].update({\n',
                '        "base_channels": 64,\n',
                '        "norm_type": "group",\n',
                '        "activation": "mish",\n',
                '        "modern": {\n',
                '            "use_film": True,\n',
                '            "use_adain": False,\n',
                '            "attention_type": "self",\n',
                '            "cond_dim": 128\n',
                '        }\n',
                '    })\n',
                'elif SELECTED_ARCH == "smart_unet":\n',
                '    config["model"].update({\n',
                '        "base_channels": 64,\n',
                '        "smart": {\n',
                '            "use_attention": True,\n',
                '            "use_smart_filter": False,\n',
                '            "drop_skip_prob": 0.0\n',
                '        }\n',
                '    })\n',
                '\n',
                '# Guardar en configs/params.yaml\n',
                'Path("configs").mkdir(parents=True, exist_ok=True)\n',
                'with open("configs/params.yaml", "w", encoding="utf-8") as f:\n',
                '    yaml.dump(config, f, sort_keys=False, default_flow_style=False)\n',
                '\n',
                'print(f"✓ Dataset seleccionado: {DATASET_NAME.upper()}")\n',
                'print(f"  • Input dir:  {INPUT_DIR}")\n',
                'print(f"  • GT dir:     {GT_DIR}")\n',
                'print(f"  • Frames dir: {FRAMES_DIR}")\n',
                'print(f"✓ Arquitectura: {SELECTED_ARCH.upper()} ({MODEL_SIZE}) -> configs/params.yaml")\n',
                'print(f"✓ MLflow Tracking configurado offline: sqlite:///mlflow.db (mlruns)")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 5. 🔍 Inspección Visual del Dataset Seleccionado\n',
                '\n',
                'Visualizamos los pares de entrada (`Input`) y objetivo (`Ground Truth`) antes de entrenar para verificar calidad, alineación de frames y dimensiones.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import glob\n',
                'import cv2\n',
                'import matplotlib.pyplot as plt\n',
                'from pathlib import Path\n',
                'from src.data.dataset import PairedImageDataset\n',
                '\n',
                'in_dir = config["data"]["input_dir"]\n',
                'gt_dir = config["data"]["gt_dir"]\n',
                '\n',
                'try:\n',
                '    ds = PairedImageDataset(input_dir=in_dir, gt_dir=gt_dir)\n',
                '    print(f"📊 Total pares coincidentes cargados exitosamente: {len(ds)}\\n")\n',
                '    \n',
                '    n_show = min(3, len(ds))\n',
                '    fig, axes = plt.subplots(n_show, 2, figsize=(12, 4 * n_show))\n',
                '    if n_show == 1:\n',
                '        axes = [axes]\n',
                '        \n',
                '    for i in range(n_show):\n',
                '        item = ds[i]\n',
                '        # Convertir de tensor [-1, 1] (C, H, W) a uint8 [0, 255] (H, W, C)\n',
                '        img_in = ((item["input"].permute(1, 2, 0).numpy() + 1.0) * 127.5).clip(0, 255).astype("uint8")\n',
                '        img_gt = ((item["gt"].permute(1, 2, 0).numpy() + 1.0) * 127.5).clip(0, 255).astype("uint8")\n',
                '        \n',
                '        axes[i][0].imshow(img_in)\n',
                '        axes[i][0].set_title(f"Input: {item[\'filename\']} ({img_in.shape[1]}x{img_in.shape[0]})")\n',
                '        axes[i][0].axis("off")\n',
                '        \n',
                '        axes[i][1].imshow(img_gt)\n',
                '        axes[i][1].set_title(f"Ground Truth: {item[\'filename\']} ({img_gt.shape[1]}x{img_gt.shape[0]})")\n',
                '        axes[i][1].axis("off")\n',
                '        \n',
                '    plt.tight_layout()\n',
                '    plt.show()\n',
                'except Exception as e:\n',
                '    print(f"❌ Error al cargar dataset: {e}")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 6. 🚀 Ejecución del Entrenamiento\n',
                '\n',
                'Lanzamos el script `scripts/train.py` en GPU. Los mejores pesos se guardarán automáticamente en `models/<run_id>/best_model_<arch>.pth` y los logs se escribirán en `mlruns` y `sqlite:///mlflow.db`.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# Ejecutar entrenamiento con la configuración generada\n',
                '!python scripts/train.py --config configs/params.yaml --device cuda'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 7. 📈 Análisis de Curvas de Pérdida y Métricas (MLflow Local)\n',
                '\n',
                'Leemos las métricas registradas de forma 100% local desde `mlruns/` para visualizar la convergencia del entrenamiento (Loss, PSNR, SSIM, LPIPS).'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import mlflow\n',
                'from mlflow.tracking import MlflowClient\n',
                'import matplotlib.pyplot as plt\n',
                'import pandas as pd\n',
                '\n',
                '# Conectar con el MLflow SQLite local\n',
                'mlflow.set_tracking_uri("sqlite:///mlflow.db")\n',
                'client = MlflowClient("sqlite:///mlflow.db")\n',
                '\n',
                'experiments = client.search_experiments()\n',
                'print(f"Experimentos encontrados: {[e.name for e in experiments]}")\n',
                '\n',
                'if experiments:\n',
                '    exp = experiments[0]\n',
                '    runs = client.search_runs(experiment_ids=[exp.experiment_id], order_by=["start_time DESC"])\n',
                '    \n',
                '    if runs:\n',
                '        latest_run = runs[0]\n',
                '        run_id = latest_run.info.run_id\n',
                '        print(f"📊 Visualizando métricas del Run: {latest_run.info.run_name} ({run_id})\")\n',
                '        \n',
                '        metrics_to_plot = ["train/loss", "val/psnr", "val/ssim", "val/crop_lpips"]\n',
                '        fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n',
                '        axes = axes.flatten()\n',
                '        \n',
                '        for idx, m_name in enumerate(metrics_to_plot):\n',
                '            try:\n',
                '                history = client.get_metric_history(run_id, m_name)\n',
                '                if history:\n',
                '                    steps = [m.step for m in history]\n',
                '                    vals = [m.value for m in history]\n',
                '                    axes[idx].plot(steps, vals, label=m_name, color="royalblue", lw=2)\n',
                '                    axes[idx].set_title(m_name.upper())\n',
                '                    axes[idx].set_xlabel("Época")\n',
                '                    axes[idx].grid(True, alpha=0.3)\n',
                '                else:\n',
                '                    axes[idx].text(0.5, 0.5, f"Sin datos: {m_name}", ha="center")\n',
                '            except Exception as e:\n',
                '                axes[idx].text(0.5, 0.5, f"No disponible: {m_name}", ha="center")\n',
                '                \n',
                '        plt.tight_layout()\n',
                '        plt.show()\n',
                '    else:\n',
                '        print("No hay runs completados en este experimento aún.")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 8. 🔮 Inferencia HD/4K (Secuencia de Video Completa)\n',
                '\n',
                'Aplica el modelo entrenado sobre la secuencia completa extraída del video (`extracted_frames`).\n',
                '\n',
                '### 💎 Modo Tiled (Recomendado para 2K / 4K):\n',
                'Al activar `--tiled`, el frame se divide en parches con solapamiento suave, permitiendo procesar cualquier resolución sin saturar la VRAM de la GPU.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import glob\n',
                'import os\n',
                'from pathlib import Path\n',
                '\n',
                '# Buscar el último modelo guardado\n',
                'model_candidates = sorted(glob.glob("models/**/*.pth", recursive=True), key=os.path.getmtime, reverse=True)\n',
                'if model_candidates:\n',
                '    LATEST_MODEL = model_candidates[0]\n',
                '    print(f"🎯 Modelo detectado más reciente: {LATEST_MODEL}")\n',
                'else:\n',
                '    LATEST_MODEL = "models/best_model_nafnet.pth"\n',
                '    print("⚠️ No se encontró checkpoint automático, ingresa la ruta manualmente.")\n',
                '\n',
                '# =========================================================================\n',
                '# 🎛️ CONFIGURACIÓN DE INFERENCIA\n',
                '# =========================================================================\n',
                'MODEL_PATH = LATEST_MODEL            # @param {type:"string"}\n',
                'INPUT_MEDIA = config["data"]["frames_dir"] # @param {type:"string"}\n',
                'OUTPUT_MEDIA = config["data"]["output_dir"] # @param {type:"string"}\n',
                'USE_TILED = True                     # @param {type:"boolean"}\n',
                'TILE_SIZE = 512                      # @param {type:"integer"}\n',
                'OVERLAP = 64                         # @param {type:"integer"}\n',
                '\n',
                'tiled_flag = f"--tiled --tile-size {TILE_SIZE} --overlap {OVERLAP}" if USE_TILED else ""\n',
                '\n',
                '!python scripts/predict.py \\\n',
                '    --config configs/params.yaml \\\n',
                '    --model {MODEL_PATH} \\\n',
                '    --video "{INPUT_MEDIA}" \\\n',
                '    --output "{OUTPUT_MEDIA}" \\\n',
                '    --native-resolution \\\n',
                '    --device cuda \\\n',
                '    {tiled_flag}'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 9. 🖼️ Visualizador Interactivo Antes / Después (Side-by-Side)\n',
                '\n',
                'Comparación visual inmediata del frame de entrada vs el resultado generado por CopyAir.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import glob\n',
                'import cv2\n',
                'import os\n',
                'import matplotlib.pyplot as plt\n',
                'from pathlib import Path\n',
                '\n',
                '# Buscar salidas generadas\n',
                'output_dir = Path(config["data"]["output_dir"])\n',
                'if output_dir.exists():\n',
                '    out_frames = sorted(list(output_dir.glob("*.png")) + list(output_dir.glob("*.jpg")))\n',
                '    in_dir = Path(config["data"]["frames_dir"])\n',
                '    in_frames = sorted(list(in_dir.glob("*.png")) + list(in_dir.glob("*.jpg")))\n',
                '    \n',
                '    if out_frames and in_frames:\n',
                '        idx = 0\n',
                '        img_in = cv2.cvtColor(cv2.imread(str(in_frames[idx])), cv2.COLOR_BGR2RGB)\n',
                '        img_out = cv2.cvtColor(cv2.imread(str(out_frames[idx])), cv2.COLOR_BGR2RGB)\n',
                '        \n',
                '        fig, ax = plt.subplots(1, 2, figsize=(16, 8))\n',
                '        ax[0].imshow(img_in)\n',
                '        ax[0].set_title(f"ORIGINAL / INPUT ({in_frames[idx].name})", fontsize=14)\n',
                '        ax[0].axis("off")\n',
                '        \n',
                '        ax[1].imshow(img_out)\n',
                '        ax[1].set_title(f"COPYAIR RESULT ({out_frames[idx].name})", fontsize=14)\n',
                '        ax[1].axis("off")\n',
                '        \n',
                '        plt.tight_layout()\n',
                '        plt.show()\n',
                '    else:\n',
                '        print(f"Se procesó video o secuencia en: {output_dir}")\n',
                'else:\n',
                '    print("No se encontraron salidas generadas en output_dir")'
            ]
        },
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '---\n',
                '## 10. 💾 Sincronización Automática con Google Drive\n',
                '\n',
                'Guarda los pesos entrenados (`models/`), la base de datos de experimentos (`mlruns` / `mlflow.db`) y los resultados generados directamente en tu carpeta de **Google Drive**, permitiendo que aparezcan al instante en tu ordenador local vía **Google Drive Desktop**.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                'import shutil\n',
                'from pathlib import Path\n',
                '\n',
                '# Ruta destino en Google Drive (sincronizada con tu PC)\n',
                'DRIVE_BACKUP_DIR = Path("/content/drive/Othercomputers/My Computer/Tesis/datasets") / DATASET_NAME / "training_runs"\n',
                'if not DRIVE_BACKUP_DIR.parent.exists():\n',
                '    DRIVE_BACKUP_DIR = Path("/content/drive/MyDrive/CopyAir_Backups") / DATASET_NAME\n',
                '\n',
                'DRIVE_BACKUP_DIR.mkdir(parents=True, exist_ok=True)\n',
                'print(f"📁 Sincronizando hacia: {DRIVE_BACKUP_DIR} ...\\n")\n',
                '\n',
                '# 1. Copiar modelos\n',
                'if Path("models").exists():\n',
                '    shutil.copytree("models", DRIVE_BACKUP_DIR / "models", dirs_exist_ok=True)\n',
                '    print("✓ Modelos (.pth) sincronizados con Google Drive.")\n',
                '\n',
                '# 2. Copiar base de datos y experimentos MLflow\n',
                'if Path("mlruns").exists():\n',
                '    shutil.copytree("mlruns", DRIVE_BACKUP_DIR / "mlruns", dirs_exist_ok=True)\n',
                'if Path("mlflow.db").exists():\n',
                '    shutil.copy2("mlflow.db", DRIVE_BACKUP_DIR / "mlflow.db")\n',
                'print("✓ Experimentos MLflow sincronizados con Google Drive.")\n',
                '\n',
                '# 3. Copiar outputs de inferencia\n',
                'if Path(OUTPUT_DIR).exists():\n',
                '    shutil.copytree(OUTPUT_DIR, DRIVE_BACKUP_DIR / "output_inference", dirs_exist_ok=True)\n',
                '    print("✓ Resultados de inferencia sincronizados con Google Drive.")\n',
                '\n',
                'print("\\n🎉 ¡Sincronización completada! Tus archivos ya están disponibles en tu PC vía Google Drive Desktop.")'
            ]
        }
    ]
}

output_path = Path("notebooks/copyair_colab_training.ipynb")
output_path.parent.mkdir(parents=True, exist_ok=True)
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Notebook generated successfully at: {output_path}")
